###
POST /member
Content-Type: application/json
Host: localhost:8002

{
  "seq" : 1,
  "name" : "tester"
}

###
DELETE /member/1
Content-Type: application/json
Host: localhost:8002



### project

GET /project/3
Content-Type: application/json
Host: localhost:8002

###

POST /project
Content-Type: application/json
Host: localhost:8002

{
"name" : "project",
"content" : "content"
}

###
PUT /project/1
Content-Type: application/json
Host: localhost:8002

{
  "name" : "project",
  "content" : "content",
  "status" : 1
}
###

DELETE /project/1
Content-Type: application/json
Host: localhost:8002

###
GET /project/1/tasks
Content-Type: application/json
Host: localhost:8002


###
GET /project/1/task/1?memberSeq=3
Content-Type: application/json
Host: localhost:8002


###
POST /project/1/task
Content-Type: application/json
Host: localhost:8002

{
  "title": "Create Title",
  "content": "Task Content",
  "uploadFile": null,
  "milestoneSeq": 1,
  "prioritySeq": 1,
  "memberSeq": 1,
  "managers": [2, 3],
  "references": [4, 5]
}

###
DELETE /project/1/task/7?memberSeq=1
Content-Type: application/json
Host: localhost:8002

