### project 추가
#Hibernate: insert into project (content, name, status) values (?, ?, ?)
#Hibernate: select member0_.member_seq as member_s1_1_0_, member0_.name as name2_1_0_ from member member0_ where member0_.member_seq=?
#Hibernate: insert into project_member (authority, member_seq, project_seq) values (?, ?, ?)
POST /project?memberSeq=1
Content-Type: application/json
Host: localhost:8002
{
  "name" : "project",
  "content" : "content",
  "status" : 1
}

### project 삭제
#Hibernate: select projectmem0_.project_member_seq as col_0_0_ from project_member projectmem0_ left outer join member member1_ on projectmem0_.member_seq=member1_.member_seq left outer join project project2_ on projectmem0_.project_seq=project2_.project_seq where member1_.member_seq=? and project2_.project_seq=? limit ?
#Hibernate: select count(*) as col_0_0_ from project project0_ where project0_.project_seq=?
#Hibernate: select project0_.project_seq as project_1_5_0_, project0_.content as content2_5_0_, project0_.name as name3_5_0_, project0_.status as status4_5_0_ from project project0_ where project0_.project_seq=?
#Hibernate: select projectmem0_.project_seq as project_4_6_0_, projectmem0_.project_member_seq as project_1_6_0_, projectmem0_.project_member_seq as project_1_6_1_, projectmem0_.authority as authorit2_6_1_, projectmem0_.member_seq as member_s3_6_1_, projectmem0_.project_seq as project_4_6_1_, member1_.member_seq as member_s1_1_2_, member1_.name as name2_1_2_ from project_member projectmem0_ left outer join member member1_ on projectmem0_.member_seq=member1_.member_seq where projectmem0_.project_seq=?
#Hibernate: delete from project_member where project_member_seq=?
#Hibernate: delete from project where project_seq=?
DELETE /project/7?memberSeq=1
Content-Type: application/json
Host: localhost:8002


### project 수정
#Hibernate: select projectmem0_.project_member_seq as col_0_0_ from project_member projectmem0_ left outer join member member1_ on projectmem0_.member_seq=member1_.member_seq left outer join project project2_ on projectmem0_.project_seq=project2_.project_seq where member1_.member_seq=? and project2_.project_seq=? limit ?
#Hibernate: select project0_.project_seq as project_1_5_0_, project0_.content as content2_5_0_, project0_.name as name3_5_0_, project0_.status as status4_5_0_ from project project0_ where project0_.project_seq=?
PUT /project/6?memberSeq=1
Content-Type: application/json
Host: localhost:8002

{
  "name" : "modProject",
  "content" : "modify",
  "status" : 2
}

### project 조회
#Hibernate: select projectmem0_.project_member_seq as col_0_0_ from project_member projectmem0_ left outer join member member1_ on projectmem0_.member_seq=member1_.member_seq left outer join project project2_ on projectmem0_.project_seq=project2_.project_seq where member1_.member_seq=? and project2_.project_seq=? limit ?
#Hibernate: select project0_.project_seq as project_1_5_0_, project0_.content as content2_5_0_, project0_.name as name3_5_0_, project0_.status as status4_5_0_ from project project0_ where project0_.project_seq=?
GET /project/1?memberSeq=1
Content-Type: application/json
Host: localhost:8002


### project 전체 조회
#Hibernate: select project0_.project_seq as col_0_0_, project0_.name as col_1_0_ from project project0_ left outer join project_member projectmem1_ on project0_.project_seq=projectmem1_.project_seq left outer join member member2_ on projectmem1_.member_seq=member2_.member_seq where member2_.member_seq=?
GET /project/projects?memberSeq=1
Content-Type: application/json
Host: localhost:8002